//! `dejavu start` — detect the repo, prepare the cache + shims, set `DEJAVU_*`,
//! prepend the shim dir to `PATH`, and run the agent — inheriting stdio and
//! propagating its exit code.

use crate::config::Config;
use crate::env;
use crate::exec::path::prepend_dedup;
use crate::exec::shim::{generate_shims, ShimContext};
use crate::exec::spawn::normalized_exit_code;
use crate::paths::CacheLayout;
use crate::repo;
use crate::store::{Db, SessionRecord};
use crate::util::{new_id, now_rfc3339};
use anyhow::{anyhow, Context};
use std::path::PathBuf;
use std::process::Command;

pub fn launch(mut command: Vec<String>) -> anyhow::Result<i32> {
    // clap usually consumes the first `--`, but strip a lingering one just in case.
    if command.first().map(String::as_str) == Some("--") {
        command.remove(0);
    }
    if command.is_empty() {
        anyhow::bail!("no command given; usage: dejavu start <command...>");
    }

    let cwd = std::env::current_dir()?;
    let repo_root = repo::detect_repo_root(&cwd);
    let layout = CacheLayout::for_repo(&repo_root)?;
    layout
        .ensure_dirs()
        .context("failed to create the Dejavu cache")?;
    let config = Config::load(&repo_root)?;
    config.write_effective(&layout)?;

    let db = Db::open(&layout.db())?;

    let dejavu_bin = resolve_dejavu_bin()?;
    let shim_ctx = ShimContext {
        shim_dir: layout.shims_bin(),
        dejavu_bin: dejavu_bin.clone(),
        enabled: config.intercept.enabled_shims(),
    };
    let shim_count = generate_shims(&shim_ctx).context("failed to generate shims")?;

    // Login shells (`zsh -lc`, used by agents like Codex to run commands)
    // rebuild PATH via /etc/zprofile (macOS path_helper) and the user's own
    // .zprofile (e.g. brew shellenv), demoting the shim dir. The wrapper
    // ZDOTDIR sources the user's dotfiles then re-prepends the shims.
    let orig_zdotdir = std::env::var_os("ZDOTDIR")
        .map(PathBuf::from)
        .or_else(dirs::home_dir)
        .unwrap_or_default();
    let zdot = write_zdot_wrappers(&layout).context("failed to write zdot wrappers")?;

    let session_id = new_id();
    let agent_command = command.join(" ");
    // Best-effort: a failed session row must not stop the agent.
    let _ = db.upsert_session_start(&SessionRecord {
        id: session_id.clone(),
        created_at: now_rfc3339(),
        ended_at: None,
        repo_root: repo_root.to_string_lossy().into_owned(),
        agent_command: agent_command.clone(),
        raw_tokens_total: 0,
        emitted_tokens_total: 0,
        saved_tokens_total: 0,
    });

    let current_path = std::env::var_os("PATH").unwrap_or_default();
    let child_path = prepend_dedup(&layout.shims_bin(), &current_path);

    eprintln!("Dejavu active");
    eprintln!("=============");
    eprintln!("Repo   {}", repo_root.display());
    eprintln!("Shims  {shim_count} commands");
    eprintln!("Cache  {}", layout.root.display());

    let program = &command[0];
    let mut cmd = Command::new(program);
    cmd.args(&command[1..])
        .env(env::ACTIVE, "1")
        .env(env::BIN, &dejavu_bin)
        .env(env::REPO_ROOT, &repo_root)
        .env(env::CACHE_DIR, &layout.root)
        .env(env::SESSION_ID, &session_id)
        .env(env::SHIM_DIR, layout.shims_bin())
        .env(env::ORIG_ZDOTDIR, &orig_zdotdir)
        .env("ZDOTDIR", &zdot)
        .env("PATH", &child_path);

    // Inherit stdio; the child shares the controlling terminal so signals are
    // delivered to it directly by the tty.
    let status = cmd
        .status()
        .map_err(|e| anyhow!("failed to launch `{program}`: {e}"))?;

    let _ = db.end_session(&session_id, &now_rfc3339());
    Ok(normalized_exit_code(status))
}

/// The `dejavu` binary is this very process (single-binary design): shims call
/// back into it via `DEJAVU_BIN`.
fn resolve_dejavu_bin() -> anyhow::Result<PathBuf> {
    let exe = std::env::current_exe().context("could not locate the running dejavu binary")?;
    Ok(std::fs::canonicalize(&exe).unwrap_or(exe))
}

/// Write the wrapper zdot files: each sources the user's counterpart, then
/// re-prepends the shim dir so it stays first even after path_helper /
/// `brew shellenv` reorder PATH. (bash login shells cannot be wrapped this
/// way — a documented V1 limitation.)
fn write_zdot_wrappers(layout: &CacheLayout) -> std::io::Result<PathBuf> {
    let zdot = layout.zdot_dir();
    std::fs::create_dir_all(&zdot)?;
    for name in [".zshenv", ".zprofile", ".zlogin", ".zshrc"] {
        let body = format!(
            "# generated by dejavu — keep shims first on PATH in login shells\n\
             [ -f \"$DEJAVU_ORIG_ZDOTDIR/{name}\" ] && . \"$DEJAVU_ORIG_ZDOTDIR/{name}\"\n\
             [ -n \"$DEJAVU_SHIM_DIR\" ] && export PATH=\"$DEJAVU_SHIM_DIR:$PATH\"\n"
        );
        std::fs::write(zdot.join(name), body)?;
    }
    Ok(zdot)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zdot_wrappers_source_user_files_and_reprepend_shims() {
        let tmp = tempfile::tempdir().unwrap();
        let layout = CacheLayout::from_dir(tmp.path().to_path_buf());
        let zdot = write_zdot_wrappers(&layout).unwrap();
        for name in [".zshenv", ".zprofile", ".zlogin", ".zshrc"] {
            let body = std::fs::read_to_string(zdot.join(name)).unwrap();
            assert!(body.contains(&format!("$DEJAVU_ORIG_ZDOTDIR/{name}")));
            assert!(body.contains("PATH=\"$DEJAVU_SHIM_DIR:$PATH\""));
        }
    }
}
